In [2]:
#MANE : DHANWANTARI CHAVAN
#BATCH : G1
# ROLL NO.= 711


In [3]:
import numpy as np
import pandas as pd

In [4]:
df1=pd.read_csv("testmarks1.csv",index_col="RollNo",usecols=['RollNo','EDS','SON','DT',"ET",])
TM1=df1.to_numpy()
print(TM1)

[[43.05 27.79 28.7  27.79]
 [43.47 28.52 28.98 27.89]
 [42.24 28.16 28.16 25.63]
 [39.24 26.16 26.16 26.16]
 [40.9  26.03 27.27 25.65]
 [39.47 26.31 26.31 25.21]
 [41.68 25.63 27.79 25.46]
 [42.19 27.61 28.13 26.21]
 [44.75 28.35 29.83 28.21]
 [46.95 28.88 31.3  28.53]]


In [5]:
df2=pd.read_csv("testmarks2.csv",index_col="RollNo",usecols=['RollNo','SIC','AM','FE',"IC"])
TM2=df2.to_numpy()
TM2

array([[28.48, 34.18, 30.56, 22.23],
       [28.1 , 33.72, 30.68, 22.82],
       [26.16, 31.39, 28.2 , 22.53],
       [26.16, 31.39, 28.78, 20.93],
       [26.1 , 31.32, 28.22, 20.82],
       [25.45, 30.54, 27.73, 21.05],
       [26.16, 31.39, 28.01, 20.51],
       [27.44, 32.93, 28.83, 22.08],
       [28.63, 34.35, 31.03, 22.68],
       [30.35, 36.42, 31.38, 23.1 ]])

In [6]:
#ROWS AND COLUME IN ARRAY
TM2.shape

(10, 4)

In [7]:
#ADDITION OF TWO ARRAY
print(np.add(TM1,TM2))

[[71.53 61.97 59.26 50.02]
 [71.57 62.24 59.66 50.71]
 [68.4  59.55 56.36 48.16]
 [65.4  57.55 54.94 47.09]
 [67.   57.35 55.49 46.47]
 [64.92 56.85 54.04 46.26]
 [67.84 57.02 55.8  45.97]
 [69.63 60.54 56.96 48.29]
 [73.38 62.7  60.86 50.89]
 [77.3  65.3  62.68 51.63]]


In [8]:
#SUBTRACTION OF TWO ARRAY

In [9]:
print(np.subtract(TM1,TM2))

[[14.57 -6.39 -1.86  5.56]
 [15.37 -5.2  -1.7   5.07]
 [16.08 -3.23 -0.04  3.1 ]
 [13.08 -5.23 -2.62  5.23]
 [14.8  -5.29 -0.95  4.83]
 [14.02 -4.23 -1.42  4.16]
 [15.52 -5.76 -0.22  4.95]
 [14.75 -5.32 -0.7   4.13]
 [16.12 -6.   -1.2   5.53]
 [16.6  -7.54 -0.08  5.43]]


In [10]:
print(np.multiply(TM1,TM2))

[[1226.064   949.8622  877.072   617.7717]
 [1221.507   961.6944  889.1064  636.4498]
 [1104.9984  883.9424  794.112   577.4439]
 [1026.5184  821.1624  752.8848  547.5288]
 [1067.49    815.2596  769.5594  534.033 ]
 [1004.5115  803.5074  729.5763  530.6705]
 [1090.3488  804.5257  778.3979  522.1846]
 [1157.6936  909.1973  810.9879  578.7168]
 [1281.1925  973.8225  925.6249  639.8028]
 [1424.9325 1051.8096  982.194   659.043 ]]


In [11]:
print(np.divide(TM1,TM2))

[[1.51158708 0.81304857 0.93913613 1.25011246]
 [1.54697509 0.84578885 0.94458931 1.22217353]
 [1.6146789  0.89710099 0.99858156 1.13759432]
 [1.5        0.83338643 0.90896456 1.24988055]
 [1.56704981 0.83109834 0.96633593 1.23198847]
 [1.55088409 0.86149312 0.94879192 1.1976247 ]
 [1.59327217 0.81650207 0.99214566 1.24134569]
 [1.53753644 0.83844519 0.97571974 1.1870471 ]
 [1.56304576 0.82532751 0.96132775 1.24382716]
 [1.54695222 0.7929709  0.99745061 1.23506494]]


In [12]:
print(np.sqrt(TM1))

[[6.56124988 5.27162214 5.35723809 5.27162214]
 [6.59317829 5.34041197 5.38330753 5.28109837]
 [6.49923072 5.30659966 5.30659966 5.06260802]
 [6.26418391 5.11468474 5.11468474 5.11468474]
 [6.39531078 5.10196041 5.22206856 5.0645829 ]
 [6.28251542 5.12932744 5.12932744 5.02095608]
 [6.45600496 5.06260802 5.27162214 5.04579032]
 [6.49538298 5.25452186 5.30377224 5.11957029]
 [6.68954408 5.3244718  5.46168472 5.31130869]
 [6.85200701 5.37401154 5.59464029 5.34134814]]


In [13]:
mod_=np.mod(TM1,TM2)
rem_=np.remainder(TM1,TM2)
pow_=np.power(TM1,TM2)

In [14]:
print(mod_)
print(rem_)
print(pow_)

[[14.57 27.79 28.7   5.56]
 [15.37 28.52 28.98  5.07]
 [16.08 28.16 28.16  3.1 ]
 [13.08 26.16 26.16  5.23]
 [14.8  26.03 27.27  4.83]
 [14.02 26.31 26.31  4.16]
 [15.52 25.63 27.79  4.95]
 [14.75 27.61 28.13  4.13]
 [16.12 28.35 29.83  5.53]
 [16.6  28.88 31.3   5.43]]
[[14.57 27.79 28.7   5.56]
 [15.37 28.52 28.98  5.07]
 [16.08 28.16 28.16  3.1 ]
 [13.08 26.16 26.16  5.23]
 [14.8  26.03 27.27  4.83]
 [14.02 26.31 26.31  4.16]
 [15.52 25.63 27.79  4.95]
 [14.75 27.61 28.13  4.13]
 [16.12 28.35 29.83  5.53]
 [16.6  28.88 31.3   5.43]]
[[3.43206478e+46 2.24962707e+49 3.57166538e+44 1.25210974e+32]
 [1.07926698e+46 1.16853535e+49 7.19744464e+44 9.66351434e+32]
 [3.38016167e+42 3.19130930e+45 7.57950325e+40 5.48410924e+31]
 [4.91983578e+41 3.15972035e+44 6.30397014e+40 4.68983854e+29]
 [1.16406797e+42 2.15105218e+44 3.27366769e+40 2.17369713e+29]
 [4.21694918e+40 2.34687901e+43 2.39856293e+39 3.18499241e+29]
 [2.38401455e+42 1.66195304e+44 2.77535278e+40 6.82583475e+28]
 [3.94229734e+44 

In [15]:
resultarray=np.transpose(TM1)
print(resultarray)

[[43.05 43.47 42.24 39.24 40.9  39.47 41.68 42.19 44.75 46.95]
 [27.79 28.52 28.16 26.16 26.03 26.31 25.63 27.61 28.35 28.88]
 [28.7  28.98 28.16 26.16 27.27 26.31 27.79 28.13 29.83 31.3 ]
 [27.79 27.89 25.63 26.16 25.65 25.21 25.46 26.21 28.21 28.53]]


In [16]:
#HORIZONTAL STACKING

In [17]:
STACKED=np.hstack((TM1,TM2))

In [18]:
print(STACKED)

[[43.05 27.79 28.7  27.79 28.48 34.18 30.56 22.23]
 [43.47 28.52 28.98 27.89 28.1  33.72 30.68 22.82]
 [42.24 28.16 28.16 25.63 26.16 31.39 28.2  22.53]
 [39.24 26.16 26.16 26.16 26.16 31.39 28.78 20.93]
 [40.9  26.03 27.27 25.65 26.1  31.32 28.22 20.82]
 [39.47 26.31 26.31 25.21 25.45 30.54 27.73 21.05]
 [41.68 25.63 27.79 25.46 26.16 31.39 28.01 20.51]
 [42.19 27.61 28.13 26.21 27.44 32.93 28.83 22.08]
 [44.75 28.35 29.83 28.21 28.63 34.35 31.03 22.68]
 [46.95 28.88 31.3  28.53 30.35 36.42 31.38 23.1 ]]


In [19]:
#VERTICAL sTACKING

In [20]:
VSTACK=np.vstack((TM1,TM2))

In [21]:
print(VSTACK)

[[43.05 27.79 28.7  27.79]
 [43.47 28.52 28.98 27.89]
 [42.24 28.16 28.16 25.63]
 [39.24 26.16 26.16 26.16]
 [40.9  26.03 27.27 25.65]
 [39.47 26.31 26.31 25.21]
 [41.68 25.63 27.79 25.46]
 [42.19 27.61 28.13 26.21]
 [44.75 28.35 29.83 28.21]
 [46.95 28.88 31.3  28.53]
 [28.48 34.18 30.56 22.23]
 [28.1  33.72 30.68 22.82]
 [26.16 31.39 28.2  22.53]
 [26.16 31.39 28.78 20.93]
 [26.1  31.32 28.22 20.82]
 [25.45 30.54 27.73 21.05]
 [26.16 31.39 28.01 20.51]
 [27.44 32.93 28.83 22.08]
 [28.63 34.35 31.03 22.68]
 [30.35 36.42 31.38 23.1 ]]


In [22]:
#SLICING

In [23]:
SLICED_ARRAY=VSTACK[::2]

In [24]:
SLICED_ARRAY

array([[43.05, 27.79, 28.7 , 27.79],
       [42.24, 28.16, 28.16, 25.63],
       [40.9 , 26.03, 27.27, 25.65],
       [41.68, 25.63, 27.79, 25.46],
       [44.75, 28.35, 29.83, 28.21],
       [28.48, 34.18, 30.56, 22.23],
       [26.16, 31.39, 28.2 , 22.53],
       [26.1 , 31.32, 28.22, 20.82],
       [26.16, 31.39, 28.01, 20.51],
       [28.63, 34.35, 31.03, 22.68]])

In [25]:
#CONCATINATION

JOINTARRAY=np.concatenate((TM1, TM2))

In [26]:
JOINTARRAY

array([[43.05, 27.79, 28.7 , 27.79],
       [43.47, 28.52, 28.98, 27.89],
       [42.24, 28.16, 28.16, 25.63],
       [39.24, 26.16, 26.16, 26.16],
       [40.9 , 26.03, 27.27, 25.65],
       [39.47, 26.31, 26.31, 25.21],
       [41.68, 25.63, 27.79, 25.46],
       [42.19, 27.61, 28.13, 26.21],
       [44.75, 28.35, 29.83, 28.21],
       [46.95, 28.88, 31.3 , 28.53],
       [28.48, 34.18, 30.56, 22.23],
       [28.1 , 33.72, 30.68, 22.82],
       [26.16, 31.39, 28.2 , 22.53],
       [26.16, 31.39, 28.78, 20.93],
       [26.1 , 31.32, 28.22, 20.82],
       [25.45, 30.54, 27.73, 21.05],
       [26.16, 31.39, 28.01, 20.51],
       [27.44, 32.93, 28.83, 22.08],
       [28.63, 34.35, 31.03, 22.68],
       [30.35, 36.42, 31.38, 23.1 ]])

In [27]:
# Addition
print(np.add(TM1,TM2))
# Subtraction
print(np.subtract(TM1,TM2))
# Multiplication
print(np.multiply(TM1,TM2))
# Division
print(np.divide(TM1,TM2))

[[71.53 61.97 59.26 50.02]
 [71.57 62.24 59.66 50.71]
 [68.4  59.55 56.36 48.16]
 [65.4  57.55 54.94 47.09]
 [67.   57.35 55.49 46.47]
 [64.92 56.85 54.04 46.26]
 [67.84 57.02 55.8  45.97]
 [69.63 60.54 56.96 48.29]
 [73.38 62.7  60.86 50.89]
 [77.3  65.3  62.68 51.63]]
[[14.57 -6.39 -1.86  5.56]
 [15.37 -5.2  -1.7   5.07]
 [16.08 -3.23 -0.04  3.1 ]
 [13.08 -5.23 -2.62  5.23]
 [14.8  -5.29 -0.95  4.83]
 [14.02 -4.23 -1.42  4.16]
 [15.52 -5.76 -0.22  4.95]
 [14.75 -5.32 -0.7   4.13]
 [16.12 -6.   -1.2   5.53]
 [16.6  -7.54 -0.08  5.43]]
[[1226.064   949.8622  877.072   617.7717]
 [1221.507   961.6944  889.1064  636.4498]
 [1104.9984  883.9424  794.112   577.4439]
 [1026.5184  821.1624  752.8848  547.5288]
 [1067.49    815.2596  769.5594  534.033 ]
 [1004.5115  803.5074  729.5763  530.6705]
 [1090.3488  804.5257  778.3979  522.1846]
 [1157.6936  909.1973  810.9879  578.7168]
 [1281.1925  973.8225  925.6249  639.8028]
 [1424.9325 1051.8096  982.194   659.043 ]]
[[1.51158708 0.81304857 0.9

In [28]:
# Standard Deviation
print(np.std(JOINTARRAY))
#Minimum
print(np.min(JOINTARRAY))
#Summation
print(np.sum(JOINTARRAY))
#Median
print(np.median(JOINTARRAY))
#Mean
print(np.mean(JOINTARRAY))
#Mode
from scipy import stats
print("Most Frequent element=",stats.mode(JOINTARRAY)[0])
print("Number of Occarances=",stats.mode(JOINTARRAY)[1])
# Variance
print(np.var(JOINTARRAY))

5.829481532477823
20.51
2359.58
28.18
29.49475
Most Frequent element= [[26.16 31.39 26.16 20.51]]
Number of Occarances= [[3 3 1 1]]
33.982854937499994


C:\Users\Admin\AppData\Local\Temp\ipykernel_16536\1641591016.py:13: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Most Frequent element=",stats.mode(JOINTARRAY)[0])
C:\Users\Admin\AppData\Local\Temp\ipykernel_16536\1641591016.py:14: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to 

In [29]:
#STATASTICAL OPERATIONS
mean_a=np.mean(JOINTARRAY)    #mean
mean_b=np.average(JOINTARRAY)    #average
sum_a=np.sum(JOINTARRAY)       #sum
var_b=np.var(JOINTARRAY)     #variance

In [30]:
print(mean_a)   
print(mean_b)
print(sum_a)
print(var_b)

29.49475
29.49475
2359.58
33.982854937499994


In [31]:
#COPY
newarray=JOINTARRAY.copy()
print(newarray)
##modification in Original Array
JOINTARRAY[0]=100
print(JOINTARRAY)
print(newarray)

[[43.05 27.79 28.7  27.79]
 [43.47 28.52 28.98 27.89]
 [42.24 28.16 28.16 25.63]
 [39.24 26.16 26.16 26.16]
 [40.9  26.03 27.27 25.65]
 [39.47 26.31 26.31 25.21]
 [41.68 25.63 27.79 25.46]
 [42.19 27.61 28.13 26.21]
 [44.75 28.35 29.83 28.21]
 [46.95 28.88 31.3  28.53]
 [28.48 34.18 30.56 22.23]
 [28.1  33.72 30.68 22.82]
 [26.16 31.39 28.2  22.53]
 [26.16 31.39 28.78 20.93]
 [26.1  31.32 28.22 20.82]
 [25.45 30.54 27.73 21.05]
 [26.16 31.39 28.01 20.51]
 [27.44 32.93 28.83 22.08]
 [28.63 34.35 31.03 22.68]
 [30.35 36.42 31.38 23.1 ]]
[[100.   100.   100.   100.  ]
 [ 43.47  28.52  28.98  27.89]
 [ 42.24  28.16  28.16  25.63]
 [ 39.24  26.16  26.16  26.16]
 [ 40.9   26.03  27.27  25.65]
 [ 39.47  26.31  26.31  25.21]
 [ 41.68  25.63  27.79  25.46]
 [ 42.19  27.61  28.13  26.21]
 [ 44.75  28.35  29.83  28.21]
 [ 46.95  28.88  31.3   28.53]
 [ 28.48  34.18  30.56  22.23]
 [ 28.1   33.72  30.68  22.82]
 [ 26.16  31.39  28.2   22.53]
 [ 26.16  31.39  28.78  20.93]
 [ 26.1   31.32  28.22  2

In [32]:
#VIEW

newarray=JOINTARRAY.view()
print(newarray)
##modification in Original Array
JOINTARRAY[0]=100
print(JOINTARRAY)
print(newarray)

[[100.   100.   100.   100.  ]
 [ 43.47  28.52  28.98  27.89]
 [ 42.24  28.16  28.16  25.63]
 [ 39.24  26.16  26.16  26.16]
 [ 40.9   26.03  27.27  25.65]
 [ 39.47  26.31  26.31  25.21]
 [ 41.68  25.63  27.79  25.46]
 [ 42.19  27.61  28.13  26.21]
 [ 44.75  28.35  29.83  28.21]
 [ 46.95  28.88  31.3   28.53]
 [ 28.48  34.18  30.56  22.23]
 [ 28.1   33.72  30.68  22.82]
 [ 26.16  31.39  28.2   22.53]
 [ 26.16  31.39  28.78  20.93]
 [ 26.1   31.32  28.22  20.82]
 [ 25.45  30.54  27.73  21.05]
 [ 26.16  31.39  28.01  20.51]
 [ 27.44  32.93  28.83  22.08]
 [ 28.63  34.35  31.03  22.68]
 [ 30.35  36.42  31.38  23.1 ]]
[[100.   100.   100.   100.  ]
 [ 43.47  28.52  28.98  27.89]
 [ 42.24  28.16  28.16  25.63]
 [ 39.24  26.16  26.16  26.16]
 [ 40.9   26.03  27.27  25.65]
 [ 39.47  26.31  26.31  25.21]
 [ 41.68  25.63  27.79  25.46]
 [ 42.19  27.61  28.13  26.21]
 [ 44.75  28.35  29.83  28.21]
 [ 46.95  28.88  31.3   28.53]
 [ 28.48  34.18  30.56  22.23]
 [ 28.1   33.72  30.68  22.82]
 [ 26.1

In [33]:
#SEARCHING

In [34]:
np.sort(JOINTARRAY,axis=0)#Horizontally Sort

array([[ 25.45,  25.63,  26.16,  20.51],
       [ 26.1 ,  26.03,  26.31,  20.82],
       [ 26.16,  26.16,  27.27,  20.93],
       [ 26.16,  26.31,  27.73,  21.05],
       [ 26.16,  27.61,  27.79,  22.08],
       [ 27.44,  28.16,  28.01,  22.23],
       [ 28.1 ,  28.35,  28.13,  22.53],
       [ 28.48,  28.52,  28.16,  22.68],
       [ 28.63,  28.88,  28.2 ,  22.82],
       [ 30.35,  30.54,  28.22,  23.1 ],
       [ 39.24,  31.32,  28.78,  25.21],
       [ 39.47,  31.39,  28.83,  25.46],
       [ 40.9 ,  31.39,  28.98,  25.63],
       [ 41.68,  31.39,  29.83,  25.65],
       [ 42.19,  32.93,  30.56,  26.16],
       [ 42.24,  33.72,  30.68,  26.21],
       [ 43.47,  34.18,  31.03,  27.89],
       [ 44.75,  34.35,  31.3 ,  28.21],
       [ 46.95,  36.42,  31.38,  28.53],
       [100.  , 100.  , 100.  , 100.  ]])

In [35]:
np.sort(JOINTARRAY,axis=1)# Vertically Sort

array([[100.  , 100.  , 100.  , 100.  ],
       [ 27.89,  28.52,  28.98,  43.47],
       [ 25.63,  28.16,  28.16,  42.24],
       [ 26.16,  26.16,  26.16,  39.24],
       [ 25.65,  26.03,  27.27,  40.9 ],
       [ 25.21,  26.31,  26.31,  39.47],
       [ 25.46,  25.63,  27.79,  41.68],
       [ 26.21,  27.61,  28.13,  42.19],
       [ 28.21,  28.35,  29.83,  44.75],
       [ 28.53,  28.88,  31.3 ,  46.95],
       [ 22.23,  28.48,  30.56,  34.18],
       [ 22.82,  28.1 ,  30.68,  33.72],
       [ 22.53,  26.16,  28.2 ,  31.39],
       [ 20.93,  26.16,  28.78,  31.39],
       [ 20.82,  26.1 ,  28.22,  31.32],
       [ 21.05,  25.45,  27.73,  30.54],
       [ 20.51,  26.16,  28.01,  31.39],
       [ 22.08,  27.44,  28.83,  32.93],
       [ 22.68,  28.63,  31.03,  34.35],
       [ 23.1 ,  30.35,  31.38,  36.42]])

In [36]:
#Counting

In [37]:
print(np.count_nonzero(JOINTARRAY))#Return total Non Zero element
print(np.nonzero(JOINTARRAY))#Return Index
print(JOINTARRAY.size)#Total Element

80
(array([ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,
        4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,
        8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12,
       12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16,
       17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
       0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
80


In [89]:
# Data Stacking

newarray=np.stack([TM1,TM2],axis=0)
print(newarray)

[[[43.05 27.79 28.7  27.79]
  [43.47 28.52 28.98 27.89]
  [42.24 28.16 28.16 25.63]
  [39.24 26.16 26.16 26.16]
  [40.9  26.03 27.27 25.65]
  [39.47 26.31 26.31 25.21]
  [41.68 25.63 27.79 25.46]
  [42.19 27.61 28.13 26.21]
  [44.75 28.35 29.83 28.21]
  [46.95 28.88 31.3  28.53]]

 [[28.48 34.18 30.56 22.23]
  [28.1  33.72 30.68 22.82]
  [26.16 31.39 28.2  22.53]
  [26.16 31.39 28.78 20.93]
  [26.1  31.32 28.22 20.82]
  [25.45 30.54 27.73 21.05]
  [26.16 31.39 28.01 20.51]
  [27.44 32.93 28.83 22.08]
  [28.63 34.35 31.03 22.68]
  [30.35 36.42 31.38 23.1 ]]]


In [90]:
newarray=np.stack([TM1,TM2],axis=1)
print(newarray)

[[[43.05 27.79 28.7  27.79]
  [28.48 34.18 30.56 22.23]]

 [[43.47 28.52 28.98 27.89]
  [28.1  33.72 30.68 22.82]]

 [[42.24 28.16 28.16 25.63]
  [26.16 31.39 28.2  22.53]]

 [[39.24 26.16 26.16 26.16]
  [26.16 31.39 28.78 20.93]]

 [[40.9  26.03 27.27 25.65]
  [26.1  31.32 28.22 20.82]]

 [[39.47 26.31 26.31 25.21]
  [25.45 30.54 27.73 21.05]]

 [[41.68 25.63 27.79 25.46]
  [26.16 31.39 28.01 20.51]]

 [[42.19 27.61 28.13 26.21]
  [27.44 32.93 28.83 22.08]]

 [[44.75 28.35 29.83 28.21]
  [28.63 34.35 31.03 22.68]]

 [[46.95 28.88 31.3  28.53]
  [30.35 36.42 31.38 23.1 ]]]


In [91]:
#Append

In [92]:
np.append(TM1,TM2,axis=0)

array([[43.05, 27.79, 28.7 , 27.79],
       [43.47, 28.52, 28.98, 27.89],
       [42.24, 28.16, 28.16, 25.63],
       [39.24, 26.16, 26.16, 26.16],
       [40.9 , 26.03, 27.27, 25.65],
       [39.47, 26.31, 26.31, 25.21],
       [41.68, 25.63, 27.79, 25.46],
       [42.19, 27.61, 28.13, 26.21],
       [44.75, 28.35, 29.83, 28.21],
       [46.95, 28.88, 31.3 , 28.53],
       [28.48, 34.18, 30.56, 22.23],
       [28.1 , 33.72, 30.68, 22.82],
       [26.16, 31.39, 28.2 , 22.53],
       [26.16, 31.39, 28.78, 20.93],
       [26.1 , 31.32, 28.22, 20.82],
       [25.45, 30.54, 27.73, 21.05],
       [26.16, 31.39, 28.01, 20.51],
       [27.44, 32.93, 28.83, 22.08],
       [28.63, 34.35, 31.03, 22.68],
       [30.35, 36.42, 31.38, 23.1 ]])

In [93]:
np.append(TM1,TM2,axis=1)

array([[43.05, 27.79, 28.7 , 27.79, 28.48, 34.18, 30.56, 22.23],
       [43.47, 28.52, 28.98, 27.89, 28.1 , 33.72, 30.68, 22.82],
       [42.24, 28.16, 28.16, 25.63, 26.16, 31.39, 28.2 , 22.53],
       [39.24, 26.16, 26.16, 26.16, 26.16, 31.39, 28.78, 20.93],
       [40.9 , 26.03, 27.27, 25.65, 26.1 , 31.32, 28.22, 20.82],
       [39.47, 26.31, 26.31, 25.21, 25.45, 30.54, 27.73, 21.05],
       [41.68, 25.63, 27.79, 25.46, 26.16, 31.39, 28.01, 20.51],
       [42.19, 27.61, 28.13, 26.21, 27.44, 32.93, 28.83, 22.08],
       [44.75, 28.35, 29.83, 28.21, 28.63, 34.35, 31.03, 22.68],
       [46.95, 28.88, 31.3 , 28.53, 30.35, 36.42, 31.38, 23.1 ]])

In [38]:
#Concatination 

concatinated=pd.concat([df1,df2],axis=1)
print(concatinated)

          EDS    SON     DT     ET    SIC     AM     FE     IC
RollNo                                                        
801     43.05  27.79  28.70  27.79  28.48  34.18  30.56  22.23
802     43.47  28.52  28.98  27.89  28.10  33.72  30.68  22.82
803     42.24  28.16  28.16  25.63  26.16  31.39  28.20  22.53
804     39.24  26.16  26.16  26.16  26.16  31.39  28.78  20.93
805     40.90  26.03  27.27  25.65  26.10  31.32  28.22  20.82
806     39.47  26.31  26.31  25.21  25.45  30.54  27.73  21.05
807     41.68  25.63  27.79  25.46  26.16  31.39  28.01  20.51
808     42.19  27.61  28.13  26.21  27.44  32.93  28.83  22.08
809     44.75  28.35  29.83  28.21  28.63  34.35  31.03  22.68
810     46.95  28.88  31.30  28.53  30.35  36.42  31.38  23.10


In [40]:
#Merge

merged=pd.merge(df1,df2,how="left")

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False